### ISSUE TITLE
Add hook for reload theme

### ISSUE THREAD

**Issue by joamjoamjoam** [suchmememanyskill/SDH-CssLoader#24]
I wrote a python script that converts images from a "theme root/images" into css files and updates the theme.json file to allow these images to be selectable as a "dropdown" patch. It also adds the user selected images as :root variable so they can be used in theming. With it i created a wallpapers theme that lets you set your own images for any wallpaper just by dropping them into an images folder. 

You guys have said that you dont want to support a image dropdown type so im looking for another way to get that functionality in the most userfriendly way possible.  if not directly supported here i can implement a seperate plugin that does the local image hosting and expose an image dropdown type. If i creted a seperate pligin it would be nice to have cooperstion between the two since they are closely related. 

So these are some of the possible options 1 is preferred:

1. Allow a theme to call a python script when the reload themes button is pressed. (Hook) this would require bundling that script with the theme. 
2. If bundling python with a theme is not wanted then the python code i wrote could be integrated into the reload themes function directly. 
3. I can create a plugin that runs this code directly (potentially even hosting the images locally) that will update a theme with the images css files. If this route is chosen an images folder and the templateTheme.json would need to be bundled with the theme in the store for it to be user friendly. With it theme creators can also bundle more than one image with a theme and user can change pictures in real time. 

I have a working prototype of the functionality here:
[Wallpapers Theme](https://github.com/joamjoamjoam/SteamDeckThemes/tree/main/Wallpapers%20Theme/Wallpapers)

Open to any and all suggestions on how we can accomplish this and will contribute where needed to make it happen. 

Thanks

**Comment by suchmememanyskill** [comment]
Loading arbitrairy python code sounds out of scope for this project. It is as the name suggests, a css loader

**Comment by joamjoamjoam** [comment]
Yeah but the python is there to make theming easier to implement. I can understand why you wouldnt want python code bundled and thsts why i intend to mak a plugin to suport this. Would you be willing to accept an images folder and themeTemplate json file with theme submissions?

**Comment by EMERALD0874** [comment]
Your comment is not relevant to this issue. Also, at least close it properly @suchmememanyskill, smh.

To add to what @suchmememanyskill said, we already denied your request of allowing custom strings for security reasons. I don't understand why allowing custom Python execution would be any more secure. Also, [you directly acknowledged that we have no plans to allow code injection](https://github.com/suchmememanyskill/SDH-CssLoader/issues/12) yet made this issue. 
﻿
Justifying a suggestion with a feature we already stated we have no intention to add also makes no case for your request. If you want us to implement local image hosting, make an issue about that and wait until we have a consensus about how we wish to approach it. Please don't make an issue asking us to allow custom code execution because we haven't finished researching your issue.
﻿
Finally, while we understand the spirit of open source is to allow anyone to make as many additions as they please, your comments seem like "implement this or I will do it myself in a way that violates your wishes for security and I would like your cooperation". It is infuriating for us to tell you no multiple times and for you to decide to try to circumvent our wishes anyways.
﻿
We will get to #20 when we have time. **Do not create multiple issues for the same topic.**

**Comment by EMERALD0874** [comment]
Locking this issue for going off-topic.
