### ISSUE TITLE
Themes not installing

### ISSUE THREAD

**Issue by dizzyflames** [suchmememanyskill/SDH-CssLoader#48]
I just downloaded the css loader from the decky loader but I can’t install any themes. I’ll click the install button but nothing happens. Anyone know how I can fix this?

**Comment by GlaZedBelmont** [comment]
Same thing happens here, fresh install and no themes install

**Comment by suchmememanyskill** [comment]
![Screenshot_20221120-120945_Chrome_1.png](https://user-images.githubusercontent.com/38142618/202898882-d0783b22-f087-48d6-8bfd-d1600963c424.png)

It seems like we hit our data caps for today, but this seems extremely weird.

Our cloudflare stats do not match our backblaze stats. Is this an intentional attack on our services?

According to backblaze also, 0 bytes of data got transfered

**Comment by suchmememanyskill** [comment]
Issue resolved. Caps reset
