### ISSUE TITLE
CSS Loader Startup error

### ISSUE THREAD

**Issue by zhouLife** [suchmememanyskill/SDH-CssLoader#81]
Error loading CSS Loader
ReferenceError: DFL is not defined
![QQ图片20230518211647](https://github.com/suchmememanyskill/SDH-CssLoader/assets/47948826/707b7797-cdbf-4274-b758-f7fca6698d8c)
![QQ图片20230518212120](https://github.com/suchmememanyskill/SDH-CssLoader/assets/47948826/1935dfe4-f78b-4fad-9828-817f241df9f3)

**Comment by PartyWumpus** [comment]
That's probably because you're using the testing version of css loader on stable decky. Either get the normal version of css loader or update decky to prerelease.

**Comment by beebls** [comment]
It errors as the testing store version of CSSLoader is using the WIP implementation of global decky-frontend-lib. This is something that is a collaboration between us and the Decky team, and we're using testing store CSSLoader as a way to test and iron out bugs.

For anyone else experiencing this, you can either:
- Use the normal store version of CSSLoader
- Install pre-release decky (or any version >= 2.9.0)

Closing as this isn't an issue but instead intentional.
